### ISSUE TITLE
Date cells not shown properly

### ISSUE THREAD

**Issue by corny** [westonganger/rodf#41] opened 2021-05-10 16:08 UTC
When I insert `Date` values into a cell, I see integers in Libre Office.

**Comment by westonganger** [comment] 2021-12-21 06:46
Closing as this is likely a duplicate of #19. Basically the recommendation at the current time is to pass in a String instead of Date or Time unless anyone knows how to handle this better.

**Closed by westonganger** 2021-12-21 06:46 UTC
